### PR TITLE
Fix warning: Unknown prop `onEdit` on <input> tag

### PR DESCRIPTION
**Pull request by zhaqiang**

### CODE REVIEW

**Comment by bebraw** [comment]
The `{...props}` pattern is there for a reason, but we could refactor it out. Another way to solve the warning would be to extract it from props before it gets to `input`. I have to give this some careful thought.

Thanks for pointing this out.

**Comment by zhaqiang** [comment]
@bebraw OK. I am going to close this PR.

**Comment by bebraw** [comment]
No worries. I'll try to get this fixed in the next few days. 👍

**Comment by jcmoraisjr** [comment]
@bebraw regarding the warning, just to let you know I changed the first line of `render()` from:

    const {value, ...props} = this.props;

to:

    const {value, onEdit, ...props} = this.props;

This way `onEdit` was removed from `...props` and Everything worked like a charm.

**Pull request closed without merging**
